
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:guessnumber
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

mybatis:
  type-aliases-package: com.twschool.practice.entity
  configuration:
    map-underscore-to-camel-case: true